### ISSUE TITLE
Benchmark market community with sample data from pylimit-orderbook

### ISSUE THREAD

**Issue by mitchellolsthoorn** [mitchellolsthoorn/tribler#9]

**Comment by joswinter** [comment]
We can't test the market community implementation using the [pylimit-orderbook sample data](https://github.com/danielktaylor/PyLimitBook/tree/master/sample_data) because the pylimit-orderbook implementation is a centralized system and our system is decentralized. In a decentralized system you can't be 100% sure whether a trade will be made because not every peer is connected to every other peer.

We can however use the pylimit-orderbook sample data to benchmark our market community implementation.
- [X] Filter pylimit-orderbook sample data so we can use it to benchmark our system.
- [x] Make it possible to parse the sample data.
- [x] Make it possible to simulate asks and bids in the market community.
- [ ] Analyze benchmark results.

**Comment by joswinter** [comment]
We decided to use random data instead of this data set because of the random nature of the decentralized experiment
